---
- name: deploy docker container
  hosts: all
  become: false

  roles:
    - docker-install
  tasks:
    - meta: flush_handlers
    # Перезапустить ssh сессию необходимо для того, чтобы применились изменения (добавление пользователя в группу docker)
    - meta: reset_connection
    - include_role:
        name: docker-deploy
